server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
  datasource:
    url: jdbc:mysql://localhost:8989/test
    username: dev
    password: dev
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      max-active: 15
      max-age: 60000
      max-idle: 2
      max-wait: 10000
      min-idle: 2
      initial-size: 2
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: "SELECT 1"
      validation-query-timeout: 1000
  sql:
    init:
      mode: always
